# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=200)),
                ('siteURL', models.CharField(max_length=200)),
                ('searchSyntax', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteURL', models.CharField(max_length=200)),
                ('jobTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('jobId', models.CharField(max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('recurrence', models.CharField(default='Daily', max_length=300)),
                ('status', models.CharField(default='SCHEDULED', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SITE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('recurrence', models.CharField(blank=True, max_length=5, null=True)),
                ('search_start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
