# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SITE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('recurrence', models.CharField(blank=True, max_length=5, null=True)),
                ('search_start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
