# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-02 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=200)),
                ('siteURL', models.CharField(max_length=200)),
                ('searchSyntax', models.CharField(blank=True, max_length=200, null=True)),
                ('jobTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('jobCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('salaryInfo', models.CharField(blank=True, max_length=200, null=True)),
                ('yearsOfExp', models.CharField(blank=True, max_length=200, null=True)),
                ('jobPostedDate', models.CharField(blank=True, max_length=200, null=True)),
                ('companyName', models.CharField(blank=True, max_length=200, null=True)),
                ('companyDomainAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('jobURL', models.CharField(blank=True, max_length=200, null=True)),
                ('jobDesc', models.CharField(blank=True, max_length=200, null=True)),
                ('aboutCompany', models.CharField(blank=True, max_length=200, null=True)),
                ('numOfJob', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
