# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerui', '0002_jobparser'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteURL', models.CharField(max_length=200)),
                ('jobTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('jobId', models.CharField(max_length=300)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('recurrence', models.CharField(default='Daily', max_length=300)),
                ('status', models.CharField(default='PENDING', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='aboutCompany',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='companyDomainAddress',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='jobCategory',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='jobDesc',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='jobPostedDate',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='jobURL',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='numOfJob',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='salaryInfo',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='yearsOfExp',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='zipcode',
        ),
    ]
