# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-06 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerui', '0003_auto_20180305_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobparser',
            name='jobTitle',
        ),
        migrations.RemoveField(
            model_name='jobparser',
            name='location',
        ),
    ]
