# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-28 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_taskscheduler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskscheduler',
            name='periodic_task',
        ),
        migrations.DeleteModel(
            name='TaskScheduler',
        ),
    ]
