class TaskState:
    PENDING = "PENDING"
    STARTING= "STARTING"
    STARTED = "STARTED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    REVOKED = "REVOKED"
    RETRY   = "RETRY"